name = "screen-share-worker"
main = "worker.js"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "ROOM_SIGNALING"
class_name = "SignalingRoom"

[[migrations]]
tag = "v1"
new_classes = ["SignalingRoom"]
